version: '3'

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=partner-service
    ports:
      - "5432:5432"
    networks:
      - scdps-network

networks:
  scdps-network:
    driver: bridge

volumes:
  minio_data:
    driver: local