server:
  port: 8090
  servlet:
    context-path: /partner-service/api

spring:
  application:
    name: scd-partner-service
  datasource:
    url: jdbc:postgresql://localhost:5400/partner-service?currentSchema=public
    username: partner-service
    password: v17461dn447f6y4w87bos
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      issuer: scd-partner-service
      secret: m6pG:7)jalI2Ig`ZpU5Q^1`
      expirationHours: 1

minio:
  url: http://localhost:9090
  bucket: partner-service
  access-key: schedy
  secret-key: x1p398h14314x3m
  auto-create-bucket: true
  connect-timeout: 10000
  write-timeout: 60000
  read-timeout: 10000
  folder-names:
    users: /s3/partner-service/users
    jobs: /s3/partner-service/jobs
  actual-minio-urls:
    users: /users
    jobs: /jobs

logging:
  level:
    org.hibernate.orm.connections.pooling: error